### ISSUE TITLE
Please release null relations fix

### ISSUE THREAD

**Issue by mreevo** [l8nite/JsonApi#10]
I require the update committed here for fixing null relations:
https://github.com/l8nite/JsonApiNet/commit/e688fcdb36ff18d6544936a368c35e1374011151

Could you please create a new nuget version?

**Comment by l8nite** [comment]
Working on it now, thanks

**Comment by l8nite** [comment]
https://www.nuget.org/packages/JsonApiNet/3.0.0

**Comment by mreevo** [comment]
Great - thank you!
