### ISSUE TITLE
How to implement this api format for all the API calls??

### ISSUE THREAD

**Issue by abiram21** [l8nite/JsonApi#17]
var article = JsonApi.ResourceFromDocument<Article>(json);
Assert.AreEqual("JSON API paints my bikeshed!", article.Title);

Where should i write this code??

**Comment by l8nite** [comment]
This is an example of how to deserialize a JSON document into an object.
You would substitute the json parameter for wherever you are getting your
JSON-API data from (i.e., reading a response from an API).

Your code probably doesn’t need the Assert, it is just demonstrating that
you can access named properties from the object (the Title in this example).

Hope that helps!

**Comment by abiram21** [comment]
Thank you very much!!!
