### ISSUE TITLE
JsonApiNet set property with no setter

### ISSUE THREAD

**Issue by jparks1** [l8nite/JsonApi#3]
Shaun, I submitted a PR for a bug fix that we have encountered. The issue is that if you pass a document that has an attribute that maps to a POCO property with no setter, a null reference exception occurs. We would expect the deserializer to just bypass the property. In this case the property with no setter has a getter from another property so when accessed, it actually has a value, just not the value in the original document.

**Comment by l8nite** [comment]
Merged it in, I'll see if I can get a release done next week (I'm remote this week without a windows machine to test/build on)
